//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobportal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class experience
    {
        public int expiid { get; set; }
        public Nullable<int> resumekey { get; set; }
        public string companyname { get; set; }
        public Nullable<System.DateTime> doj { get; set; }
        public Nullable<int> yoe { get; set; }
        public string jobtitle { get; set; }
        public string responsibilities { get; set; }
    
        public virtual register register { get; set; }
    }
}
