//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobportal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobsubmission
    {
        public int submissionid { get; set; }
        public Nullable<int> resumekey { get; set; }
        public Nullable<int> reqid { get; set; }
        public Nullable<bool> selected { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<bool> assessmentstatus { get; set; }
        public Nullable<System.DateTime> appliedon { get; set; }
    
        public virtual req req { get; set; }
        public virtual register register { get; set; }
    }
}
