//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobportal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jobportalEntities1 : DbContext
    {
        public jobportalEntities1()
            : base("name=jobportalEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<experience> experiences { get; set; }
        public virtual DbSet<jobsubmission> jobsubmissions { get; set; }
        public virtual DbSet<qualification> qualifications { get; set; }
        public virtual DbSet<register> registers { get; set; }
        public virtual DbSet<req> reqs { get; set; }
    }
}
