//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jobportal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualification
    {
        public int qid { get; set; }
        public Nullable<int> resumekey { get; set; }
        public string Qualification1 { get; set; }
        public string institutename { get; set; }
        public Nullable<System.DateTime> YOC { get; set; }
    
        public virtual register register { get; set; }
    }
}
